name = "cf-hono-llm"
compatibility_date = "2024-03-29"
main = "src/index.ts"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "past_KV"
id = "bc4dcc7e532448aa8f4e0c5fa0502682"

 [vars]
[vars]
GPT_API_KEY = ""
GPT_BASE = ""
