name = "cf-hono-llm"
compatibility_date = "2024-03-29"
main = "src/index.ts"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "PKV"
id = "bc4dcc7e532448aa8f4e0c5fa0502682"

# [vars]
# Please set them as the secret in cloudflare
# API_KEY = "YOUR_JWT_TOKEN"
# GPT_BASE = "GPT_HTTP_URL"
