name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20 and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"  # CORRECTED: Enable pnpm caching, set up node.

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          projectDir: ./     #If you kept your wrangler.toml in the same directory
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

